# Generated by Django 2.2.16 on 2022-07-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_lower_register_role'),
        ('reviews', '0003_auto_20220717_1047'),
    ]

    operations = [
    ]
